---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    keyname: "jenkins"
    inventory_path: "{{ lookup('env', 'WORKSPACE') }}/rpc-gating/playbooks/inventory"
    user_data_path: "{{ lookup('env', 'WORKSPACE') }}/rpc-gating/scripts/user_data_pubcloud.sh"
    cloud_name: "public_cloud"
    boot_timeout: "{{ lookup('env', 'BOOT_TIMEOUT') | default(900, true) }}"
  tasks:

    - name: Create inventory directory
      file:
        path: "{{ inventory_path }}"
        state: directory

    # regions, and fallback_regions should be CSV strings
    # We randomly shuffle them both, then use the first
    # item of the resulting lists for the try/rescue block.

    - name: Create primary region list
      set_fact:
        # replace: replace commas with spaces. Double spaces will be removed by trim or select.
        # split on spaces to produce a list
        # trim: remove spaces from beginning and end of each item
        # upper: convert to upper case
        # select: remove empty strings from the list
        # shuffle: randomise order
        regions_shuff: >-
          {{- (regions | replace(',', ' ')).split() | map('trim') | map('upper') | select | shuffle }}

    - name: Create fallback region list
      set_fact:
        # if there is only one item in the list, use it - even if it's in the first list
        # otherwise, use the difference filter to exclude the first item in regions_shuff
        # because that region has already failed
        fallback_regions_shuff: >-
          {%- set region_list = (fallback_regions | replace(',', ' ')).split() | map('trim') | map('upper') | select | shuffle %}
          {{- (region_list | length == 1) | ternary(region_list, region_list | difference([regions_shuff[0]])) }}

    - name: Determine the latest image name when required
      when:
        - image | match('^nodepool-.*')
      block:
        - name: Get the list of images
          os_image_facts:
            cloud: "{{ cloud_name }}"
            region_name: "{{ regions_shuff[0] }}"
          register: _images

        - name: Set the image name fact
          set_fact:
            _image: "{{ _images.ansible_facts.openstack_image | json_query('[*].name') | select('match', image ~ '*') | list | sort | last }}"

    - name: Provision a cloud instance
      block:
        - name: Output the primary region list
          debug:
            msg: "Job-provided primary regions: {{ regions }}; Resulting shuffled regions: {{ regions_shuff }}"

        - name: Fail when no primary regions are provided
          fail:
            msg: "No primary regions were provided. Please review job configuration."
          when:
            - regions_shuff | length == 0

        - name: Provision a cloud instance (first primary region)
          os_server:
            name: "{{ instance_name }}"
            flavor: "{{ flavor }}"
            state: present
            cloud: "{{ cloud_name }}"
            region_name: "{{ regions_shuff[0] }}"
            image: "{{ _image | default(image) }}"
            key_name: "{{ keyname }}"
            userdata: "{{ lookup('file', user_data_path) }}"
            config_drive: yes
            meta:
              build_config: core
            wait: yes
            timeout: "{{ boot_timeout }}"
          register: _instance_provision

        - name: Write inventory
          copy:
            content: |
              [job_nodes:children]
              hosts

              [hosts]
              {{ _instance_provision.server.name }} ansible_host={{ _instance_provision.server.accessIPv4 }} ansible_user=root rax_region={{ _instance_provision.server.region }}
            dest: '{{ inventory_path }}/hosts'

        - name: Wait for SSH connectivity to the cloud instance (10 min timeout)
          wait_for:
            timeout: 600
            port: 22
            host: "{{ _instance_provision.server.accessIPv4 }}"
            sleep: 10
            search_regex: "OpenSSH"

      rescue:
        - name: Ensure first attempt instance is removed.
          os_server:
            name: "{{ instance_name }}"
            state: absent
            cloud: "{{ cloud_name }}"
            region_name: "{{ regions_shuff[0] }}"
            wait: yes
            timeout: "{{ boot_timeout }}"

        - name: Output the fallback region list
          debug:
            msg: "Job-provided secondary regions: {{ fallback_regions }}; Resulting shuffled regions: {{ fallback_regions_shuff }}"

        - name: Fail when no fallback regions are provided
          fail:
            msg: "No fallback regions were provided. Please review job configuration."
          when:
            - fallback_regions_shuff | length == 0

        - name: Provision a cloud instance (first fallback region)
          os_server:
            name: "{{ instance_name }}"
            flavor: "{{ flavor }}"
            state: present
            cloud: "{{ cloud_name }}"
            region_name: "{{ fallback_regions_shuff[0] }}"
            image: "{{ _image | default(image) }}"
            key_name: "{{ keyname }}"
            userdata: "{{ lookup('file', user_data_path) }}"
            config_drive: yes
            meta:
              build_config: core
            wait: yes
            timeout: "{{ boot_timeout }}"
          register: _instance_provision

        - name: Write inventory
          copy:
            content: |
              [job_nodes:children]
              hosts

              [hosts]
              {{ _instance_provision.server.name }} ansible_host={{ _instance_provision.server.accessIPv4 }} ansible_user=root rax_region={{ _instance_provision.server.region }}
            dest: '{{ inventory_path }}/hosts'

        - name: Wait for SSH connectivity to the fallback cloud instance (10 min timeout)
          wait_for:
            timeout: 600
            port: 22
            host: "{{ _instance_provision.server.accessIPv4 }}"
            sleep: 10
            search_regex: "OpenSSH"

    - name: Show results of instance provision task
      debug:
        var: _instance_provision

    - name: Add Host
      add_host:
        hostname: "singleuseslave"
        ansible_ssh_host: "{{ _instance_provision.server.accessIPv4 }}"

    - name: Show generated inventory
      debug:
        msg: "Generated inventory: {{ lookup('file', inventory_path+'/hosts')}}"

    - name: Wait for host preparation to complete
      pause:
        minutes: 5

# Note(odyssey4me):
# We use the raw module for this Ansible play because
# we do not know if python and python-yaml are on the
# system yet, and Ansible requires those installed to
# use any modules other than raw.
- hosts: singleuseslave
  remote_user: root
  gather_facts: False
  tasks:
    # To assist with debugging any problems if there
    # is an apt failure, we set enable debugging.
    - name: Add apt debug configuration
      raw: echo 'Debug::Acquire::http "true";' > /etc/apt/apt.conf.d/99debug
      args:
        executable: /bin/bash

    - name: Check whether python is present on the host
      raw: |
        if [[ -e /usr/bin/python ]]; then
          echo -n yes
        else
          echo -n no
        fi
      register: _python_check

    - name: Show the results of the python check
      debug:
        var: _python_check

    - name: Install python onto the host if it is not already present
      when:
        - "not (_python_check.stdout | trim) | bool"
      block:
        # The apt sources in the OnMetal builds uses
        # archive.ubuntu.com which has turned out to
        # be a bit unreliable in providing complete
        # data back when doing apt updates/installs.
        # We prefer our local mirror which provides
        # us with reliable and quick responses.
        # ref: RE-1758
        - name: Reconfigure the host to use Rackspace Mirrors
          script: "{{ playbook_dir }}/../scripts/reconfigure_apt_sources.sh"

        - name: Check the resulting apt sources file
          raw: cat /etc/apt/sources.list
          args:
            executable: /bin/bash
          register: _apt_sources_result

        - name: Show the resulting apt sources file
          debug:
            var: _apt_sources_result

        - name: Update apt cache
          raw: apt-get update
          args:
            executable: /bin/bash
          register: _update_cache
          until: _update_cache is success
          retries: 3
          delay: 15

        # We check to see whether the packages are available
        # and where they will come from.
        # ref: RE-1758
        - name: Check the package candidates
          raw: apt-cache policy python-minimal python-yaml
          args:
            executable: /bin/bash
          register: _package_candidates

        - name: Show the package candidates
          debug:
            var: _package_candidates

        - name: Install minimal Ansible requirements so that Ansible can be used to setup the slave
          raw: apt-get install -y python-minimal python-yaml
          args:
            executable: /bin/bash
          register: _install_packages
          until: _install_packages is success
          retries: 3
          delay: 15
